### ISSUE TITLE
tensorrt是怎样优化的  onnx是怎样工作的  ？哪里有入门资料？git

### ISSUE THREAD

**Issue by henbucuoshanghai** [Stephenfang51/tracklite#1]

**Comment by Stephenfang51** [comment]
> _No description provided._

这部分我没办法给你什么好建议， 也不太能在issue里说个明白
建议参考官方的文档， 或者一些博客（当然要选对的）
maybe之后我会在知乎上整合一些TensorRT的使用方法等 谢谢你issue
